#include "sdl.h"

#define SCANCODE_UP SDL_SCANCODE_UP
#define SCANCODE_DOWN SDL_SCANCODE_DOWN
#define SCANCODE_LEFT SDL_SCANCODE_LEFT
#define SCANCODE_RIGHT SDL_SCANCODE_RIGHT

#define SCANCODE_A SDL_SCANCODE_A
#define SCANCODE_B SDL_SCANCODE_S
#define SCANCODE_START SDL_SCANCODE_RETURN
#define SCANCODE_SELECT SDL_SCANCODE_APOSTROPHE